### PR TITLE
Fix #124: Symfony 3 : The helper "dialog" is not defined

### LINKED ISSUE #124: Symfony 3 : The helper "dialog" is not defined
Hi,

I think compatibility with symfony 3 is broken

Changelog symfony: **deprecated the dialog helper (use the question helper instead)**

```bash
bin/console swiftmailer:email:send -vvv
[2015-12-24 15:59:05] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".  
[2015-12-24 15:59:05] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".  
[2015-12-24 15:59:05] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".  


                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The helper "dialog" is not defined.                             
                                                                  


Exception trace:
 () at /srv/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/HelperSet.php:79
 Symfony\Component\Console\Helper\HelperSet->get() at /srv/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:608
 Symfony\Component\Console\Command\Command->getHelper() at /srv/www/symfony/vendor/symfony/swiftmailer-bundle/Command/NewEmailCommand.php:88
 Symfony\Bundle\SwiftmailerBundle\Command\NewEmailCommand->interact() at /srv/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at /srv/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:804
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /srv/www/symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/www/symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /srv/www/symfony/bin/console:29

```

Thanks,

### PR DESCRIPTION
**Pull request by aarnaud**

### CODE REVIEW

**Comment by xabbuh** [comment]
This will break applications with Symfony 2.3 where the `Question` class does not exist.

**Comment by stof** [comment]
Indeed. Please write the code in a way supporting both APIs.

**Comment by sstok** [comment]
FYI. https://github.com/rollerworks/PasswordStrengthBundle/blob/master/src/Command/BlacklistPurgeCommand.php#L48-L53

**Comment by aarnaud** [comment]
thanks @sstok

**Comment by sstok** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @aarnaud.

**Pull request closed without merging**
