### PR TITLE
Add retry logic to the memory spool

### PR DESCRIPTION
**Pull request by Seldaek**
Just a suggestion.. depending on the backend, network timeouts or minor service outages can occur sometimes, and then emails don't get delivered which is quite bad. Re-trying a few times like this is fairly harmless and can get rid of most such minor issues.

### CODE REVIEW

**Comment by xtuc** [comment]
Nice job. 
As you said it depends on the backend, the maximum retry number should be configurable (`swiftmailer.mailer.%s.transport.retries` for example).

I think the number of failed retries should be indicated in the log entry.
`Exception occurred while flushing email queue: %s (after %d retries)`

**Comment by Seldaek** [comment]
Yeah let's see what people want in terms of configurability.. I think it's good enough as is for the very intermittent failures (we get those every few days with Amazon SES, sending quite a lot of email..).

**Comment by xtuc** [comment]
Yes ok. Anyway, this will be fine for the most cases.

**Comment by fabpot** [comment]
Isn't it something that should be in Swiftmailer instead?

**Comment by Seldaek** [comment]
That's well possible :) I'll take a look later.

**Comment by Seldaek** [comment]
Moved over to https://github.com/swiftmailer/swiftmailer/pull/749

**Pull request closed without merging**
