### PR TITLE
decode username and password from url

### PR DESCRIPTION
**Pull request by eeemarv**
#234

### CODE REVIEW

**Comment by naderman** [comment]
@eeemarv stof suggested you do this instead: https://github.com/symfony/swiftmailer-bundle/issues/270#issuecomment-448266067

**Comment by eeemarv** [comment]
Now using rawurlencode() and including host.

**Comment by naderman** [comment]
In summary, this PR fixes https://github.com/symfony/swiftmailer-bundle/issues/234 https://github.com/symfony/swiftmailer-bundle/issues/270 and https://github.com/symfony/swiftmailer-bundle/issues/276

**Comment by eeemarv** [comment]
Sorry, I just noticed the naming of the commit is wrong. It should be "rawurlDECode() host, username and password" instead of "rawurlencode". In the code it is correct, though.

**Comment by eeemarv** [comment]
Note the [query part is already urldecoded](https://github.com/symfony/swiftmailer-bundle/blob/5daf79b9e331b45c1d03564f83a1a3a015b7ab8e/DependencyInjection/SwiftmailerTransportFactory.php#L119) as the [parse_str() function](https://www.php.net/manual/en/function.parse-str.php) does this.

**Comment by naderman** [comment]
@fabpot I know you're focused on Mailer these days, but mind merging this? I think it's a somewhat common problem to run into on a current Symfony4 project, e.g. when following the docs on sending email with GMail https://github.com/symfony/symfony-docs/blob/master/email.rst#using-gmail-to-send-emails this will not currently work if a password contains non-ascii characters, even if they get encoded.

**Comment by fabpot** [comment]
Thank you @eeemarv.

**Pull request merged**
