### PR TITLE
Fix compat with Symfony 5 - bump to Symfony ^4.3.8|^5.0

### PR DESCRIPTION
**Pull request by nicolas-grekas**
To be tagged as 3.4 then.

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by TomasVotruba** [comment]
Why this package is released under 3.4 but not compatible with any other 3.4 packages?

**Comment by fabpot** [comment]
@TomasVotruba The versioning of this bundle does not follow the Symfony versioning as it is not part of symfony/symfony (like other bundles outside of the main repo -- MonologBundle for instance).

**Comment by TomasVotruba** [comment]
Why?

**Pull request merged**
